name: Run project tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: docker build -t cl-commonmark .
    - name: Run tests
      run: docker run --rm cl-commonmark sbcl --eval '(asdf:test-system "commonmark")'
